### ISSUE TITLE
Electricity | Installing the BTE

### ISSUE THREAD

**Issue by iteles** [ideaq/home#63]
We have had approval from EDP to increase the electricity supply to the house (although not as much as we would like but of course we will have #20 + #25) and the next step is to have all of the new equipment installed that EDP requires in order to provide us with electricity from the grid. 

This is now quite high priority as it is a pre-cursor to having a decent electrical output in the house.

These were the two steps outlined in the letter from EDP:

![image](https://user-images.githubusercontent.com/4185328/55291658-eade7680-53d8-11e9-980b-b97133dc3ff5.png)

Step 1 is to install the BTE (Baixa Tensão Especial), for which we'll need electricians and a construction worker to knock into the garden wall (where it needs to be installed) without compromising it. After this, EDP will come for an inspection, let us know what else is required and hook everything up.

## Tasks
+ [x] Get estimated budgets for the work
+ [x] Confirm order of steps that need to be taken are as above **[in progress - email sent]**
+ [x] Book installation of BTE date
+ [ ] Call EDP and confirm installation date, booking date for visit/inspection
  + [ ] Get clarification from BTE on how the tariff structure works and whether we can be on 'normal' electricity with the BTE installed before we have to start paying the fixed monthly fees associated with a higher electricity consumption until we need it: https://www.edpsu.pt/pt/tarifasehorarios/pages/tarifasbte.aspx
+ [ ] BTE installation
+ [ ] EDP visit
+ [ ] Get next steps from EDP

_Note: Further information on BTEs here: https://lojaluz.com/faq/baixa-tensao-especial-media-tensao 🇵🇹 _

**Comment by iteles** [comment]
Currently awaiting confirmation on the steps proposed above from our electricians.

This is chiefly so that we know exactly how much money this will cost and when. 
Installing the BTE is under €1000 (independent of the electricians we choose, quotes have ranged from €700 - €950). The _rest_ of the work required post BTE installation has been quoted at €5-6,000 + IVA of unexpected costs (depending on whether we cover the inspections separately or not) so making sure we are splitting out the steps correctly will allow us to ask for a couple of other quotes to understand whether this is within the right ballpark or not.

**Comment by iteles** [comment]
Awaiting confirmation from our electrician of whether the inspection he has budgeted for includes the inside of the house as well as the connection to the BTE. 
There are also open questions on who will install the ITED box and the same question about the ITED box inspection as for the BTE. 

Chased again today.

**Comment by iteles** [comment]
Meeting with electricians and BTE installers at the building site on Friday (26-Apr-2019) to finally move this forward.

**Comment by iteles** [comment]
Meeting went well, second pass of quotes expected on Monday 29-Apr-2019.

**Comment by iteles** [comment]
I am officially slightly baffled by the disparity in quotes flying around here:

+ We've had one quote to install the BTE box for €800 + IVA (Bruno, recommended by Bernardo)
  + This is _just the box_, doesn't include making the hole in the exterior (stone) wall _or_ connecting the box to the EDP 'ramal' exterior to the house, though he has estimated this at €600 maximum (no guarantees until the work is defined by EDP though)
+ The other quote (Jorge) is for €2950 + IVA
  + It also _doesn't_ include the hole in the exterior wall but _does_ include the connection to the EDP 'ramal'. In fact, it includes exactly this:  
![image](https://user-images.githubusercontent.com/4185328/57161515-b7ca4100-6de3-11e9-9356-4b8e5a8b5767.png)

Both have confirmed that the work can be done next week.

Under the assumption that the BTE box costs around €800 to install (as per the first quote), either the second quote is a joke or I don't understand enough about this and there is some massive portion of the work that I am missing/misunderstanding and would cost us an unexpected small fortune if we were to go with the first quote.

I have spoken to our 'overseer' and agreed we would call the second quote company together on Monday to make sure we're not missing anything.

A decision on this _must_ be made this week.

**Comment by iteles** [comment]
We went with the €800+IVA quote but I'm officially waiting for the other shoe to drop. We'll see!

Closing in favour of #70
